// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonCourriel.API.Data;

#nullable disable

namespace MonCourriel.API.Migrations
{
    [DbContext(typeof(MonCourrielDbContext))]
    partial class MonCourrielDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MonCourriel.API.Models.Courrier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Adresse")
                        .HasColumnType("longtext");

                    b.Property<string>("CodeCourrier")
                        .HasColumnType("longtext");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateCourrier")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Expediteur")
                        .HasColumnType("longtext");

                    b.Property<string>("MailCourrier")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("Obejt")
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Courriers");
                });

            modelBuilder.Entity("MonCourriel.API.Models.CourrierImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourrierId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NameImg")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CourrierId");

                    b.ToTable("CourrierImages");
                });

            modelBuilder.Entity("MonCourriel.API.Models.Directions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CompagnyDirections");
                });

            modelBuilder.Entity("MonCourriel.API.Models.Recommandation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("recommandations");
                });

            modelBuilder.Entity("MonCourriel.API.Models.ServicesDep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("DirectionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("ServicesDeps");
                });

            modelBuilder.Entity("MonCourriel.API.Models.CourrierImage", b =>
                {
                    b.HasOne("MonCourriel.API.Models.Courrier", "Courriers")
                        .WithMany("CourrierImages")
                        .HasForeignKey("CourrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courriers");
                });

            modelBuilder.Entity("MonCourriel.API.Models.ServicesDep", b =>
                {
                    b.HasOne("MonCourriel.API.Models.Directions", "Directions")
                        .WithMany("ServicesDeps")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directions");
                });

            modelBuilder.Entity("MonCourriel.API.Models.Courrier", b =>
                {
                    b.Navigation("CourrierImages");
                });

            modelBuilder.Entity("MonCourriel.API.Models.Directions", b =>
                {
                    b.Navigation("ServicesDeps");
                });
#pragma warning restore 612, 618
        }
    }
}
